name: CI Actions
on: [push]
jobs:

  Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
